name: geeksday
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Porcent Indicator
  percent_indicator: ^3.0.1
  #like button in the posts
  like_button: ^2.0.2
  #Choose image and take photos with the camera
  image_picker: ^0.8.3+2
  # Avatars
  multiavatar: ^0.1.5
  #Circular Loader
  progress_indicators: ^1.0.0
  #Password generator
  random_password_generator: ^0.2.1

  
  ## UUID Generator
  uuid: ^3.0.4
  ## Online storage
  firebase_storage: ^10.0.1
  ## Online NoSQL Database
  cloud_firestore: ^2.4.0
  ## Online Auth service
  firebase_auth: ^3.0.1
  # Compare objects
  equatable: ^2.0.3
  # Local storage 
  shared_preferences: ^2.0.6
  # State Management
  flutter_bloc: ^7.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Support Firebase Google Signin
  google_sign_in: ^5.0.7
  # Process Blob Images
  image_whisperer: ^0.11.1
  #provider pack for light and dark theme
  provider: ^6.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_svg: ^0.22.0
  rive: ^0.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/like.svg
    - assets/icons/is_liked.svg
    - assets/icons/comment.png
    - assets/icons/home.svg
    - assets/icons/search.svg
    - assets/icons/plus.svg
    - assets/icons/events.svg
    - assets/icons/user.svg
    - assets/rive/guategeeks_logo.riv

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Biryani
  #     fonts: 
  #       - assets/fonts/Biryani-Black.ttf
  #       - assets/fonts/Biryani-Bold.ttf
  #       - assets/fonts/Biryani-ExtraBold.ttf
  #       - assets/fonts/Biryani-ExtraLight.ttf
  #       - assets/fonts/Biryani-Light.ttf
  #       - assets/fonts/Biryani-Regular.ttf
  #       - assets/fonts/Biryani-SemiBold.ttf
  fonts:
    - family: Biryani
      fonts:
        - asset: assets/fonts/biryani/Biryani-Regular.ttf
        - asset: assets/fonts/biryani/Biryani-Black.ttf
        - asset: assets/fonts/biryani/Biryani-Bold.ttf
        - asset: assets/fonts/biryani/Biryani-ExtraBold.ttf
        - asset: assets/fonts/biryani/Biryani-ExtraLight.ttf
        - asset: assets/fonts/biryani/Biryani-Light.ttf
        - asset: assets/fonts/biryani/Biryani-SemiBold.ttf
    - family: Abel
      fonts:
        - asset: assets/fonts/abel/Abel-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
